### PR TITLE
Initial files

### PR DESCRIPTION
**Pull request by job13er**
### This project uses [semver](semver.org), please check the scope of this pr:
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change
# CHANGELOG
- **Added** validator code from `ember-frost-bunsen`

### CODE REVIEW

**Comment by job13er** [comment]
@sandersky self-merging initial port of some validator stuff from `ember-frost-bunsen`. After your PR is merged, I'll try consuming this inside `ember-frost-bunsen` I'm a little concerned about using `npm` to load `z-schema` in the consuming app context, but we'll see how it goes.

**Comment by job13er** [comment]
👍

**Comment by sandersky** [comment]
@job13er I believe what you will need to do to have `z-schema` play nice with Ember as an npm dependency is add this to your `index.js` in `ember-frost-bunsen`.

``` js
  treeForAddon (tree) {
    var zSchemaPath = path.dirname(require.resolve('z-schema/src/ZSchema.js'))
    var zSchemaTree = this.treeGenerator(zSchemaPath)

    var trees = mergeTrees([zSchemaTree, tree], {
      overwrite: true
    })

    return this._super.treeForAddon.call(this, trees)
  }
```

This is how `ember-lodash` is able to wire in `lodash` as an npm dependency: https://github.com/levanto-financial/ember-lodash/blob/master/index.js#L10-L19

**Comment by job13er** [comment]
Cool, thanks @sandersky

**Pull request merged**
