### PR TITLE
Fix publish to include lib

### PR DESCRIPTION
**Pull request by sandersky**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [x] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG

* **Fixed** Travis config to run build script.

### CODE REVIEW

**Comment by sophypal** [comment]
@sandersky I could have sworn this was being run.  Otherwise, the test wouldn't run since it needs the `lib` and that's done before it's published.

**Comment by sandersky** [comment]
@sophypal it [looks like the tagged commits don't run tests in TravisCI](https://travis-ci.org/ciena-blueplanet/bunsen-core/jobs/297032880) and thus the build never happens on the CI run that deploys to npm.

**Comment by sophypal** [comment]
@sandersky Good discovery. 👍

**Comment by sandersky** [comment]
:shit: it looks like the install was skipped in the tag commit and thus didn't publish

**Pull request merged**
