### PR TITLE
Added uint64 validation support

### PR DESCRIPTION
**Pull request by cstolli**
### This project uses [semver](semver.org), please check the scope of this pr:
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change
# CHANGELOG
- added uint64 format validation support

### CODE REVIEW

**Comment by cstolli** [comment]
@mdahl I did this by simply checking that the number is between 0 and Number.MAX_SAFE_INTEGER, is there a better way?  L3VPN wants this validation format.

**Comment by sandersky** [comment]
@cstolli I think this will validate part of the uint 64-bit range but not all of it. Technically a JavaScript number is signed 64-bit so it can't support the full uint 64-bit range so given the input is a number this should be fine. However in reality the `format` JSON Schema property tends to be used with a String which doesn't have the same limitation. I think what we will really need is a smarter function that will match a string input to a Regex for validating between 0 and the max uint 64-bit value, `18,446,744,073,709,551,615`. I think that Regex will look something like:

```
/^(\d{1,19}|1[1-7]\d{18}|18[1-3]\d{17}|184[1-3]{16}|1844[1-5]{15}|…)$/
```

Note: the above regex is not complete, hence the `…`.

**Review by sophypal — COMMENTED** [review]
Using regex for this seems rather horrendous to me. If we also need to support larger ranges like `uint128`, this method won't scale. Why don't we look into a BigInt library that gives us the capability to operate on such large numbers. Here's one https://www.npmjs.com/package/big-integer.

**Comment by sandersky** [comment]
@sophypal what are your thoughts on doing something like:

``` js
const MAX_VALUE = '18446744073709551615'

/**
 * Validate value as an unsigned 64-bit integer
 * @param {Any} value - value to validate
 * @returns {Boolean} whether or not value is valid
 */
export default function (value) {
  value = `${value}`

 // Ensure value is a natural number (positive integers)
  if (!/^\d+$/.test(value)) {
    return false
  }

 // If value has less digits than max value then we can safely say it is valid
  if (value.length < MAX_VALUE.length) {
    return true
  }

 // If value has more digits than max value then we can safely say it is not valid
  if (value.length > MAX_VALUE.length) {
    return false
  }

  const firstHalf = parseInt(value.substr(0, 10))
  const secondHalf = parseInt(value.substr(10))

  return !(
    firstHalf > 1844674407 ||
    (firstHalf === 1844674407 && secondHalf > 3709551615)
  )
}
```

The only thing this implementation doesn't take into account is leading zeros but I'm not sure whether or not we care about those.

**Comment by sandersky** [comment]
Also @cstolli  I'd love to see the following numbers added as failure test cases:
- 18446744073709551616
- 18446744073709551625
- 18446744073709551715
- 18446744073709552615
- 18446744073709561615
- 18446744073709651615
- 18446744073719551615
- 18446744073809551615
- 18446744074709551615
- 18446744083709551615
- 18446744173709551615
- 18446745073709551615
- 18446754073709551615
- 18446844073709551615
- 18447744073709551615
- 18456744073709551615
- 18546744073709551615
- 19446744073709551615
- 28446744073709551615

**Pull request merged**
