### PR TITLE
Allow more value types on the selectRenderer options and allow /multicast in mac mask validation

### PR DESCRIPTION
**Pull request by sophypal**
### This project uses [semver](semver.org), please check the scope of this pr:
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change
# CHANGELOG
- **Fixed** Selects can be used with values other than string. This adds supports for numbers and booleans.

### CODE REVIEW

**Comment by sophypal** [comment]
@sandersky Do you think we should support all types as well?

**Comment by sandersky** [comment]
@sophypal I think we should definitely add `integer` to the list. If we can get it working with `object` as well that'd be pretty cool.

**Comment by sandersky** [comment]
Not sure if we should add tests the verify validation passes with the new types?

**Comment by sandersky** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/bunsen-core/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/bunsen-core)

**Comment by sophypal** [comment]
@sandersky So I've added `integer` and `object` as a valid type. Made sure I did the same for the `none` option as well as add test. I want to get your feedback on the `multicast` feature I added in the `mac` validation. I know it's none standard to have `multicast` as a mask but the alternative is to have the application inject it's own custom formats and I can see this being useful in other applications.

**Comment by sandersky** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/bunsen-core/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/bunsen-core)

**Pull request merged**
